projeto_um:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: athena-421420
      dataset: dbt_dw
      threads: 4
      keyfile: /usr/local/airflow/projeto_um/athena-421420-766e358f4b1e.json